//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.UnitConversion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET/", ConfigurationName="UnitConversion.lengthUnitSoap")]
    public interface lengthUnitSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ChangeLengthUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double ChangeLengthUnit(double LengthValue, WebService.UnitConversion.Lengths fromLengthUnit, WebService.UnitConversion.Lengths toLengthUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ChangeLengthUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ChangeLengthUnitAsync(double LengthValue, WebService.UnitConversion.Lengths fromLengthUnit, WebService.UnitConversion.Lengths toLengthUnit);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Lengths {
        
        /// <remarks/>
        Angstroms,
        
        /// <remarks/>
        Nanometers,
        
        /// <remarks/>
        Microinch,
        
        /// <remarks/>
        Microns,
        
        /// <remarks/>
        Mils,
        
        /// <remarks/>
        Millimeters,
        
        /// <remarks/>
        Centimeters,
        
        /// <remarks/>
        Inches,
        
        /// <remarks/>
        Links,
        
        /// <remarks/>
        Spans,
        
        /// <remarks/>
        Feet,
        
        /// <remarks/>
        Cubits,
        
        /// <remarks/>
        Varas,
        
        /// <remarks/>
        Yards,
        
        /// <remarks/>
        Meters,
        
        /// <remarks/>
        Fathoms,
        
        /// <remarks/>
        Rods,
        
        /// <remarks/>
        Chains,
        
        /// <remarks/>
        Furlongs,
        
        /// <remarks/>
        Cablelengths,
        
        /// <remarks/>
        Kilometers,
        
        /// <remarks/>
        Miles,
        
        /// <remarks/>
        Nauticalmile,
        
        /// <remarks/>
        League,
        
        /// <remarks/>
        Nauticalleague,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface lengthUnitSoapChannel : WebService.UnitConversion.lengthUnitSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class lengthUnitSoapClient : System.ServiceModel.ClientBase<WebService.UnitConversion.lengthUnitSoap>, WebService.UnitConversion.lengthUnitSoap {
        
        public lengthUnitSoapClient() {
        }
        
        public lengthUnitSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public lengthUnitSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lengthUnitSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lengthUnitSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ChangeLengthUnit(double LengthValue, WebService.UnitConversion.Lengths fromLengthUnit, WebService.UnitConversion.Lengths toLengthUnit) {
            return base.Channel.ChangeLengthUnit(LengthValue, fromLengthUnit, toLengthUnit);
        }
        
        public System.Threading.Tasks.Task<double> ChangeLengthUnitAsync(double LengthValue, WebService.UnitConversion.Lengths fromLengthUnit, WebService.UnitConversion.Lengths toLengthUnit) {
            return base.Channel.ChangeLengthUnitAsync(LengthValue, fromLengthUnit, toLengthUnit);
        }
    }
}
